customhost = "database-1.coghw13fheqo.us-east-2.rds.amazonaws.com"
customuser = "admin"
custompass = "root1234"
customdb = "employee"
custombucket = "addemp-1"
customregion = "us-east-2"
customtable = "employee_image_table"
